### ISSUE TITLE
Dynamis force spawn zone boss not working - Bastok

### ISSUE THREAD

**Issue by BloodlustShiva** [bnetcc/DSPVanilla#1]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30190305_0

**_Source Branch_** (master/stable) **:** 
No idea

 ffxi.cc
**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Traded Steelwall Bijou to the ??? listed on wikia in Dynamis - Bastok, zone boss does not appear.

**Comment by tagban** [comment]
Howdy! I opened up !getid command so we can capture the ID of the ??? and figure out whats going on. When you have a chance please do that. Also if you recall what the name of the megaboss is that will help me also.

**Comment by Ninjistix** [comment]
i think i found when it broke again maybe

https://github.com/DarkstarProject/darkstar/commit/eced170444f4494bc4482ad738523fd51000a40d

**Comment by tagban** [comment]
This is actually confirmed not to be meant to work. Apparently DSP runs on Pre 2011 Dynamis scripts when things had changed.
